hooks:
  # Available:
  # - WorldGuard - provides worldguard area adapter
  enabled:
    - "WorldGuard"

area:
  # Available:
  # - fishy - Build-in, only rectangles
  # - worldguard - Requires WorldGuard, more shapes
  enabled-adapters:
    - "fishy"

version: 1
