hooks:
  # Available:
  # - WorldGuard - Provides worldguard area adapter
  # - PlaceholderAPI - Support for messages and whatnot
  # - Vault - Provides vault reward adapter
  enabled:
    - "WorldGuard"

rewards:
  # Available:
  # - command - Allows executing commands as form of reward (can be used with PlaceholderAPI hook for placeholder support)
  # - vault - Allows you to give players currency (Vault hook needs to be enabled as well as a plugin that provider Vault economy)
  # - message - Allows you to send a message to player or everyone as a form of reward (supports PlaceholderAPI hook)
  enabled-adapters:
    - "command"
    - "message"

area:
  # Available:
  # - fishy - Build-in, only rectangles
  # - worldguard - Requires WorldGuard, more shapes
  enabled-adapters:
    - "fishy"

inventory:
  mask:
    storage:
      - "xxxxxxxxx"
      - "xxxxxxxxx"
      - "xxxxxxxxx"
    hotbar:
      - "xxxxrxxxx"
  items:
    x:
      type: AIR
    r:
      type: FISHING_ROD
      name: "&e&lFishy Rod"
      lore:
        - "&7Use it to fish for amazing rewards!"
      unbreakable: true
      flags:
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_ENCHANTS
      enchants:
        - type: "unbreaking"
          level: 1

version: 1
