hooks:
  # Available:
  # - WorldGuard - Provides worldguard area adapter
  # - PlaceholderAPI - Support for messages and whatnot
  # - Vault - Provides vault reward adapter
  enabled:
    - "WorldGuard"

rewards:
  # Available:
  # - command - Allows executing commands as form of reward (can be used with PlaceholderAPI hook for placeholder support)
  # - vault - Allows you to give players currency (Vault hook needs to be enabled as well as a plugin that provider Vault economy)
  # - message - Allows you to send a message to player or everyone as a form of reward (supports PlaceholderAPI hook)
  # - actionbar - Same as message
  # - title - Allows you to send a title message to player or everyone (also supports PlaceholderAPI hook)
  # - points - Allows you to give players internal points
  # - container - Allows you to give multiple rewards at once
  # - item - Allows you to give items as rewards
  enabled-adapters:
    - "command"
    - "message"
    - "title"
    - "actionbar"
    - "points"
    - "container"
    - "item"

  displays:
    command:
      type: PAPER
      name: "&e&lCommand &7(${name})"
      enchants:
        - type: "unbreaking"
          level: 1
    vault:
      type: SUNFLOWER
      name: "&a&l${amount}"
      enchants:
        - type: "unbreaking"
          level: 1
    points:
      type: PAPER
      name: "&a&l${amount}"
      enchants:
        - type: "unbreaking"
          level: 1
    container:
      type: CHEST
      name: "&6&lRewards"
      enchants:
        - type: "unbreaking"
          level: 1
    message:
      type: AIR
    title:
      type: AIR
    actionbar:
      type: AIR
    item:
      type: AIR # Dynamic

area:
  # Available:
  # - fishy - Build-in, only rectangles
  # - worldguard - Requires WorldGuard, more shapes
  enabled-adapters:
    - "fishy"

points:
  enabled: true

inventory:
  mask:
    storage:
      - "xxxxxxxxx"
      - "xxxxxxxxx"
      - "xxxxxxxxx"
    hotbar:
      - "xxxxrxxxx"
  items:
    x:
      type: AIR
    r:
      type: FISHING_ROD
      name: "&e&lFishy Rod"
      lore:
        - "&7Use it to fish for amazing rewards!"
      unbreakable: true
      flags:
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_ENCHANTS
      enchants:
        - type: "unbreaking"
          level: 1

version: 1
