name: FishyBusiness
version: '${version}'
main: com.github.kaspiandev.fishybusiness.FishyBusiness
api-version: '1.19'
author: KaspianDev
softdepend: [ Vault, WorldGuard, PlaceholderAPI, POBox ]
libraries:
  - dev.dejvokep:boosted-yaml:1.3.5
commands:
  fishybusiness:
    aliases: [ fbs ]
