name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Generate tag name
      run: echo "TAG_NAME=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Upload JAR to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${TAG_NAME}
        files: ./build/libs/FishyBusiness-*.jar
        token: ${{ secrets.RELEASE_TOKEN }}
