name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Set tag name
      id: tag_name
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Upload JAR to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_name.outputs.sha_short }}
        files: ./build/libs/FishyBusiness-*.jar
        token: ${{ secrets.RELEASE_TOKEN }}
